name:                bench-tool
version:             0.4.0.1
github:              "haskell-grpc-native/http2-grpc-haskell"
license:             BSD3
author:              "Lucas DiCioccio, Alejandro Serrano"
maintainer:          "lucas@dicioccio.fr"
copyright:           "2017 - 2020 Lucas DiCioccio, Alejandro Serrano"

extra-source-files:
- README.md
- ChangeLog.md

synopsis:            Benchmarking gRPC client tool
category:            Networking

description:         Please see the README on Github at <https://github.com/haskell-grpc-native/http2-grpc-haskell/blob/master/warp-grpc/README.md>

dependencies:
- base >= 4.10 && < 5
- async >= 2.2.1 && < 3
- binary >= 0.8.5 && < 0.9
- bytestring >= 0.10.8 && < 0.11
- case-insensitive >= 1.2.0 && < 1.3
- http2 >= 1.6 && < 3
- http2-grpc-types >= 0.5 && < 0.6
- http-types >= 0.12 && < 0.13
- unliftio-core >= 0.1 && < 0.3
- proto-lens-runtime
- proto-lens
- http2-client-grpc
- http2-grpc-proto-lens
- http2-client
- microlens
- text
- containers
- http2-grpc-proto3-wire
- proto3-wire
- warp
- warp-tls
- warp-grpc
- optparse-generic
- lifted-base
- lifted-async

library:
  source-dirs: src
  ghc-options: -Wall

executables:
  bench-tool-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -O2
    dependencies:
    - bench-tool
